project:
  type: website
  output-dir: docs

website:
  title: "Using Data science to improve inclusion and diversity in organizations"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: Linked In
        href: https://www.linkedin.com/in/siddarth-subrahmanian/
format:
  html:
    theme: cosmo
    css: styles.css



